# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - group: add-iterations-to-azure-devops-project

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - '*'
    exclude:
    - 'README.md'
pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  displayName: 'Run the PowerShell script'
  inputs:
    filePath: '$(build.sourcesdirectory)/createIterations.ps1'
    arguments: -Organization "$(Organization)" -PAT "$(PAT)" `
      -Project "$(Project)" `
      -TeamName "$(TeamName)" `
      -YearOfIteration "$(YearOfIteration)" `
      -MonthOfIteration "$(MonthOfIteration)" `
      -StartDateOfIteration "$(StartDateOfIteration)" `
      -NumberOfSprints "$(NumberOfSprints)"